#! /bin/dash

run() {
	if ! pgrep "$1" ;
	then
		"$@"
	fi
}

export SXHKD_SHELL=/bin/dash
# KILL
killall sxhkd
killall compton
killall st
killall pavucontrol
killall dunst

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           12

bspc config normal_border_color  "#2a2228"
bspc config focused_border_color "#ffe0b2"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config history_aware_focus  true

bspc rule -a Firefox desktop='^3' follow=on
bspc rule -a qutebrowser desktop='^3' state=maximised follow=on
bspc rule -a Lutris desktop='^4' follow=on
bspc rule -a Steam desktop='^4' follow=on
bspc rule -a Wine desktop='^4' state=floating
bspc rule -a Mixbus32C desktop='^2' state=floating follow=on
bspc rule -a Mixbus32c-4.3.19 state=floating layer=above
bspc rule -a Pavucontrol desktop='^5'
bspc rule -a Spotify desktop='^5'
bspc rule -a discord desktop='^10'
bspc rule -a Slack desktop='^10'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Dunst layer=above

# START
sxhkd > /dev/null 2>&1 &
run compton > /dev/null 2>&1 &
run feh --bg-fill /home/jozan/Pictures/wallpaper.jpg > /dev/null 2>&1 &
setxkbmap -layout us,fr -option grp:alt_shift_toggle
xset r rate 200 80 > /dev/null 2>&1 &
numlockx on > /dev/null 2>&1
run dunst > /dev/null 2>&1 &
run mpd &
#mopidy &
#sleep 1
#bspc desktop -f '^8'
#st -e ncmpcpp &
sleep 0.3
bspc desktop -f '^5'
st -e ncpamixer &
sleep 0.3
bspc desktop -f '^2'
st -e zsh -c 'TERM=xterm-256color; emacs -nw' &
sleep 0.3
bspc desktop -f '^1'
st -e /home/jozan/.cargo/bin/ytop -s &
sleep 0.1
st &
sleep 0.1
st -e vifm &
sleep 0.1
bspc node -f west
bspc node -z right -200 0
sleep 0.1
bspc node -f east
bspc node -z top 0 120
sleep 0.1
bspc node -f north

if wget -q --spider https://gentoo.org/; then
	/usr/bin/discord --no-sandbox &
fi
