#!/usr/local/bin/dash

source /home/jozan/.profile

run() {
	if ! pgrep "$1";
	then
		"$@"
	fi
}

# KILL
pkill st
pkill compton
pkill xcompmgr

/home/jozan/.local/bin/dualscreen
dual=$?
sleep 1

if [ $dual -eq 0 ]; then
	bspc monitor LVDS-1 -d 04 05 06 07 08 09 10
	bspc monitor VGA-1 -d 01 02 03
	# bspc monitor VGA1 -d 01 02 03 04 05 06 07 08 09 10
else
	bspc monitor LVDS-1 -d 01 02 03 04 05 06 07 08 09 10
fi

bspc config border_width		1
bspc config window_gap			0

bspc config focused_border_color	\#b92121

bspc config split_ratio			0.50
bspc config borderless_monocle	true
bspc config gapless_monocle		true
bspc config single_monocle		true

if [ $dual -eq 0 ]; then
	bspc rule -a Firefox desktop=05 follow=true
	bspc rule -a Wine desktop=06 state=floating
else
	bspc rule -a Firefox desktop=03 follow=on
	bspc rule -a Wine desktop=04 state=floating
fi
bspc rule -a Dunst layer=above
bspc rule -a Zathura state=tiled
bspc rule -a qTox desktop=09
bspc rule -a DergodsRealmII desktop=4 state=floating

# START
# run sxhkd > /dev/null 2>&1 &
run compton >/dev/null 2>&1 &
# run xcompmgr >/dev/null 2>&1 &
setxkbmap -layout us,fr -option grp:alt_shift_toggle
[ $dual -eq 0 ] && \
	feh --bg-fill /home/jozan/Pictures/wallpaper.jpg --bg-fill /home/jozan/Pictures/wallpaper.jpg > /dev/null 2>&1 || \
	feh --bg-fill /home/jozan/Pictures/wallpaper.jpg > /dev/null 2>&1
xset r rate 150 100 > /dev/null 2>&1
run dunst > /dev/null 2>&1 &
# run mpd > /dev/null 2>&1 &
run ~/.local/bin/todo-git-updater.sh > /dev/null 2>&1 &
run lowbat --say "You're low, partner" > /dev/null 2>&1 &
# mopidy 2>&1 &

sleep 5

# bspc desktop -f 09
# st -e neomutt &
# sleep 1

if [ $dual -eq 0 ]; then
	# bspc desktop -f 07
	# st -e ncmpcpp &
	# sleep 0.3
	# st -e newsboat &
	# sleep 0.3
	# st -e mixertui &
	# sleep 0.3
	# st -e calcurse &
	# sleep 0.3
	# bspc node -f west
	# bspc node -f west
	# bspc node -z right -200 0
	# bspc node -f east
	# bspc node -z right -100 0
	# bspc node -z top 0 -50
	bspc desktop -f 01
else
	# bspc desktop -f 08
	# st -e ncmpcpp &
	# sleep 1
	# bspc desktop -f 07
	# st -e calcurse &
	# sleep 1
	# bspc desktop -f 06
	# st -e newsboat &
	# sleep 1
	# bspc desktop -f 05
	# st -e mixertui &
	# sleep 1
	bspc desktop -f 02
fi

# st -e zsh -c 'emacs -nw' &
run emacs &

sleep 1

if [ $dual -eq 0 ]; then
	bspc desktop -f 04
	st -e dash -c 'clear; cowsay "Welcome back, partner! And remember to try glest!"; zsh -i' &
	sleep 0.3
	st -e htop &
	sleep 0.3
	st -e gotop &
	sleep 0.3
	bspc node -p south
	st -e /usr/home/jozan/.local/bin/greptemp.sh &
	sleep 0.3
	bspc node -f west
	st -e vifm &
	sleep 0.3
	bspc node -z right 180 0
	bspc node -z top 0 70
	bspc node -f east
	bspc node -f north
	bspc node -z bottom 0 100
	bspc node -z top 0 -200
	bspc node -f north
	bspc node -f west
else
	bspc desktop -f 01
	st -e dash -c 'clear; cowsay "Welcome back, partner!"; zsh -i' &
	sleep 0.3
	bspc node -p west
	st -e htop &
	sleep 0.3
	st -e gotop &
	sleep 0.3
	bspc node -p south
	st -e /usr/home/jozan/.local/bin/greptemp.sh &
	sleep 0.3
	bspc node -f east
	st -e vifm &
	sleep 0.3
	bspc node -f west
	bspc node -f north
	bspc node -z top 0 -200
	bspc node -z bottom 0 100
	bspc node -z right -220 0
	bspc node -f east
	bspc node -z top 0 70
	bspc node -f north
fi

sleep 0.3

espeak "Welcome home" &

if curl https://www.freebsd.org/ >/dev/null 2>&1; then
	bspc desktop -f 10
	st -e slack-term &
	# run slack &
	sleep 1
	bspc desktop -f 09
	run qtox &
	sleep 1.5
	if [ $dual -eq 0 ]; then
		bspc desktop -f 04
	else
		bspc desktop -f 01
	fi
fi
