#!/bin/sh

export SXHKD_SHELL=/bin/zsh
export PATH="${HOME}/.local/bin:${PATH}"
#source /home/jozan/.zshrc

function run {
	if ! pgrep $1 ;
	then
		$@
	fi
}

# KILL
rm /home/jozan/.calcurse/.calcurse.pid
killall st

dualscreen
ret=$?
sleep 1s

if [ $ret -eq 0 ]; then
	bspc monitor LVDS1 -d 01 05 06 07 08 09 10
	bspc monitor VGA1 -d 02 03 04
else
	bspc monitor LVDS1 -d 01 02 03 04 05 06 07 08 09 10
fi

bspc config border_width		1
bspc config window_gap			0

bspc config split_ratio			0.50
bspc config borderless_monocle	true
bspc config gapless_monocle		true

bspc rule -a qutebrowser desktop=03 follow=on
bspc rule -a Firefox desktop=03 follow=on
bspc rule -a Lutris desktop=04 follow=on
bspc rule -a Steam desktop=04 follow=on
bspc rule -a Wine desktop=04 state=floating
bspc rule -a discord desktop=10
bspc rule -a Slack desktop=10
bspc rule -a Zathura state=tiled
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Dunst layer=above

# START

run sxhkd > /dev/null 2>&1 &
run compton > /dev/null 2>&1 &
run feh --bg-fill /home/jozan/Pictures/wallpaper.png > /dev/null 2>&1 &
setxkbmap -layout us,fr -option grp:alt_shift_toggle > /dev/null 2>&1
xset r rate 200 80 > /dev/null 2>&1
run dunst > /dev/null 2>&1 &
run mpd > /dev/null 2>&1 &
run lowbat > /dev/null 2>&1 &
#mopidy 2>&1 &

sleep 5s

bspc desktop -f 09
st -e neomutt &
sleep 1s

bspc desktop -f 08
st -e ncmpcpp &
sleep 1s

bspc desktop -f 07
st -e calcurse &
sleep 1s

bspc desktop -f 06
st -e newsboat &
sleep 1s

bspc desktop -f 05
st -e ncpamixer &
sleep 1s

bspc desktop -f 02
st -e zsh -c 'TERM=xterm-256color; emacs -nw' &
sleep 1s

bspc desktop -f 01
st -e gotop -b &
sleep 0.3s
st -e zsh -c 'clear; cowsay "Welcome back, partner!"; zsh -i' &
sleep 0.3s
st -e vifm &
sleep 0.3s
bspc node -f west
bspc node -z right -200 0
sleep 0.3s
bspc node -f east
bspc node -z top 0 70
sleep 0.3s
bspc node -f north
sleep 0.3s

if [ $ret -eq 0 ]; then
	bspc desktop -f 02
fi

ping -c4 gentoo.org
ret=$?
if [ $ret -eq 0 ]; then
	run slack &
fi
