#! /bin/sh

export SXHKD_SHELL=/bin/zsh
# KILL
killall sxhkd
killall compton
killall st
killall pavucontrol
killall feh
killall dusnt
killall mpd

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a qutebrowser desktop='^3' state=maximised follow=on
bspc rule -a Lutris desktop='^4' follow=on
bspc rule -a Steam desktop='^4' follow=on
bspc rule -a Wine desktop='^4' state=floating
bspc rule -a Pavucontrol desktop='^5'
bspc rule -a discord desktop='^10'
bspc rule -a Slack desktop='^10'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Dunst layer=above

# START
sxhkd > /dev/null 2>&1 &
compton > /dev/null 2>&1 &
feh --bg-fill /home/jozan/Images/wallpaper.jpg > /dev/null 2>&1 &&
#setxkbmap -layout us,fr -option grp:alt_shift_toggle &
xset r rate 200 80 > /dev/null 2>&1 &
numlockx on > /dev/null 2>&1
dunst > /dev/null 2>&1 &
mpd > /dev/null 2>&1 &
#mopidy &
sleep 4s
bspc desktop -f '^9'
st -e neomutt &
sleep 0.5s
bspc desktop -f '^8'
st -e ncmpcpp &
sleep 0.5s
bspc desktop -f '^7'
st -e calcurse &
sleep 0.5s
bspc desktop -f '^5'
st -e ncpamixer &
pavucontrol &
sleep 0.5s
bspc desktop -f '^1'
st -e gotop &
sleep 0.2s
st &
sleep 0.2s
st -e ranger &
sleep 0.2s
bspc node -f west
bspc node -z right -160 0
sleep 0.2s
bspc node -f east
bspc node -z top 0 120
sleep 0.2s
bspc node -f north
discord &
